/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NOTEBOOK_H_RPCGEN
#define _NOTEBOOK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct person_data {
	char name[128];
	char address[128];
	char phone[128];
};
typedef struct person_data person_data;

#define NOTEBOOK_PROG 69420
#define NOTEBOOK_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERT 1
extern  void * insert_1(person_data *, CLIENT *);
extern  void * insert_1_svc(person_data *, struct svc_req *);
#define LOOKUP 2
extern  person_data * lookup_1(person_data *, CLIENT *);
extern  person_data * lookup_1_svc(person_data *, struct svc_req *);
#define RESET 3
extern  void * reset_1(void *, CLIENT *);
extern  void * reset_1_svc(void *, struct svc_req *);
extern int notebook_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERT 1
extern  void * insert_1();
extern  void * insert_1_svc();
#define LOOKUP 2
extern  person_data * lookup_1();
extern  person_data * lookup_1_svc();
#define RESET 3
extern  void * reset_1();
extern  void * reset_1_svc();
extern int notebook_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_person_data (XDR *, person_data*);

#else /* K&R C */
extern bool_t xdr_person_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NOTEBOOK_H_RPCGEN */
